# Generated by Django 5.1.2 on 2024-10-19 19:09

import archmanweb.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("archmanweb", "0001_initial"),
        (
            "archmanweb",
            "0002_rename_manpage_name_lang_archmanweb__name_04c0ca_idx_and_more",
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UpdateLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("duration", models.DurationField()),
                ("updated_pkgs", models.IntegerField()),
                ("updated_pages", models.IntegerField()),
                ("stats_count_man_pages", models.IntegerField()),
                ("stats_count_symlinks", models.IntegerField()),
                ("stats_count_all_pkgs", models.IntegerField()),
                ("stats_count_pkgs_with_mans", models.IntegerField()),
                ("convert_txt_returncode", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("raw", models.TextField()),
                ("html", models.TextField(blank=True, null=True)),
                ("txt", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    archmanweb.models.SearchVectorIndex(
                        fields=["description"], name="content_description_search"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("repo", models.TextField()),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("arch", models.TextField()),
                ("description", models.TextField()),
                ("url", models.TextField(null=True)),
                ("build_date", models.DateTimeField()),
                (
                    "licenses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"], name="package_name", opclasses=["gin_trgm_ops"]
                    ),
                    archmanweb.models.SearchVectorIndex(
                        fields=["description"], name="package_description_search"
                    ),
                ],
                "unique_together": {("name", "repo")},
            },
        ),
        migrations.CreateModel(
            name="ManPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("section", models.TextField()),
                ("lang", models.TextField(default="en")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="manpage_content",
                        to="archmanweb.content",
                    ),
                ),
                (
                    "converted_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manpage_converted_content",
                        to="archmanweb.content",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archmanweb.package",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "lang", "section"],
                        name="archmanweb__name_40ba48_idx",
                    ),
                    models.Index(
                        fields=["section", "name", "lang"],
                        name="archmanweb__section_c6738f_idx",
                    ),
                    models.Index(
                        fields=["lang", "name", "section"],
                        name="archmanweb__lang_0c4ca0_idx",
                    ),
                    models.Index(
                        fields=["section", "name"],
                        name="archmanweb__section_0e8e6b_idx",
                    ),
                    models.Index(
                        fields=["name", "lang"], name="archmanweb__name_04c0ca_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name"], name="manpage_name", opclasses=["gin_trgm_ops"]
                    ),
                ],
                "unique_together": {("package", "section", "name", "lang")},
            },
        ),
        migrations.CreateModel(
            name="SymbolicLink",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("lang", models.TextField(default="en")),
                ("from_section", models.TextField()),
                ("from_name", models.TextField()),
                ("to_section", models.TextField()),
                ("to_name", models.TextField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archmanweb.package",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["from_section", "from_name"],
                        name="archmanweb__from_se_0d698b_idx",
                    ),
                    models.Index(
                        fields=["from_section", "from_name", "lang"],
                        name="archmanweb__from_se_526737_idx",
                    ),
                    models.Index(
                        fields=["from_name", "lang"],
                        name="archmanweb__from_na_214e63_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["from_name"],
                        name="symboliclink_from_name",
                        opclasses=["gin_trgm_ops"],
                    ),
                ],
                "unique_together": {("package", "lang", "from_section", "from_name")},
            },
        ),
    ]
